changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New
      labels:
        - feature
        - enhancement
    - title: Fixed
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
